config/routes.rb
Rails.application.routes.draw do
  resources :tours
  resources :areas
  resources :countries

  root 'home#index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show]  do
    member do
      get :following, :followers
    end
  end

  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :area
  validates :title, presence: true
  validates :area_id, presence: true
  validates :number_of_people, presence: true
  validates :meeting_place, presence: true
  validates :price, presence: true
  validates :time, presence: true
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]
  def index
    @tours = Tour.page(params[:page])
  end

  def show
  end

  def new
    @tour = Tour.new
  end

  def edit
  end

  def create
    @tour = Tour.new(tour_params)
    if @tour.save
      flash[:success] = "Tour posted!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    @tour.update(tour_params)
  end

  def destroy
    @tour.destroy
  end

  private
    def set_tour
      @tour = Tour.find(params[:id])
    end

    def tour_params
      params.require(:tour).permit(:title, :area_id, :recommend_one, :recommend_two, :recommend_three, :included, :number_of_people, :meeting_place, :price, :time)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= simple_form_for @tour, wrapper: :horizontal_form, html: {class: 'form-horizontal'} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :area_id, :collection => Area.all  %>
    <%= f.input :recommend_one %>
    <%= f.input :recommend_two %>
    <%= f.input :recommend_three %>
    <%= f.input :included, input_html: {rows: 10} %>
    <%= f.input :number_of_people, collection: 2..15 %>
    <%= f.input :meeting_place %>
    <%= f.input :price %>
    <%= f.input :time %>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-10">
      <%= f.button :submit, class: 'btn btn-primary' %> | <%= link_to 'Back', tours_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<h1>Listing tours</h1>

<%= page_entries_info @tours %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Area</th>
      <th>number_of_people</th>
      <th>meeting_place</th>
      <th>price</th>
      <th>time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= tour.title %></td>
        <td><%= tour.area.name %></td>
        <td><%= tour.number_of_people %></td>
        <td><%= tour.meeting_place %></td>
        <td><%= tour.price %></td>
        <td><%= tour.time %></td>
        <td><%= link_to 'Show', tour %></td>
        <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
        <td><%= link_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tour', new_tour_path %>

<br>

<%= paginate @tours %>

app/views/tours/new.html.erb
<h1>New tour</h1>

<%= render 'form' %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>title:</strong>
  <%= @tour.title %>
</p>

<p>
  <strong>Area:</strong>
  <%= @tour.area.name %>
</p>

<p>
  <strong>Reccomend one:</strong>
  <%= @tour.recommend_one %>
</p>

<p>
  <strong>Recommend two:</strong>
  <%= @tour.recommend_two %>
</p>

<p>
  <strong>Reccomend three:</strong>
  <%= @tour.recommend_three %>
</p>

<p>
  <strong>Included:</strong>
  <%= @tour.included %>
</p>

<p>
  <strong>Number of people:</strong>
  <%= @tour.number_of_people %>
</p>

<p>
  <strong>Meeting place:</strong>
  <%= @tour.meeting_place %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tour.price %>
</p>

<p>
  <strong>Time:</strong>
  <%= @tour.time %>
</p>
<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>